# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  TF_VAR_aws_region: us-east-1
  AWS_REGION: us-east-1

jobs:
  
  # Job para criar o bucket S3
  s3create:
    name: 'Criação do S3'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./IaC/S3

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./IaC/S3

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./IaC/S3
        continue-on-error: true

  # Job principal para aplicar o Terraform e criar a infraestrutura
  aplicaterraform:
    name: 'Job Principal - Aplicar Terraform'
    runs-on: ubuntu-latest
    needs: s3create

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./IaC

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./IaC

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./IaC